# -*- coding: utf-8 -*-
"""bs4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hGGXpKmCq8vfQ8pUYKH_Uzn70epMgZK
"""

pip install requests

pip install beautifulsoup4

pip install html5lib

import requests
from bs4 import BeautifulSoup
url = "https://perfectplanb.net/home"
r = requests.get(url)
htmlContent= r.content
print(htmlContent)

soup=BeautifulSoup(htmlContent, 'html.parser')
print(soup.prettify)

title = soup.title
print(title)
print(type(soup)) #3. Beautifulsoup
print(type(title)) #1. Tag
print(type(title.string)) #2. NavigableString

#get the title of the HTML page
title = soup.title
#get all the paragraphs from the page
paras = soup.find_all('p')
print(paras)

# get all the anchor tags from the page
anchors= soup.find_all('a')
all_links = set()
#print(anchors)

# get all the links on the page
for link in anchors:
  if (link.get('href')!='#'):
    linkText="https://perfectplanb.net/home" +link.get('href')
    print(linkText)

print(soup.find('p')) #get first element in the html page

print(soup.find('p')['class']) #get classes of any element of the html page

#find all elements with class para-1
print(soup.find_all("p",class_="google soci-btn"))

#get the text from the tags/soup
print(soup.find('p').get_text())

#get text of complete soup/html page
print(soup.get_text())

#comment
markup = "<p><!--this is a comment--></p>"
soup2=BeautifulSoup(markup)
print(type(soup2.p.string))